export const CartActions = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SET_KG_LIMIT: "SET_KG_LIMIT",
  SET_BACKGROUND_COLOR: "SET_BACKGROUND_COLOR",
};
